import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SimpleWebAuthnBrowser from '@simplewebauthn/browser';
import { startRegistration } from '@simplewebauthn/browser';
import {useState} from 'react';
import { startAuthentication } from '@simplewebauthn/browser';


const Home: NextPage = () => {
	const [username, setUsername] = useState('');

	const register = async () => {
	    const resp = await fetch('/api/register?username='+username);
		console.log('yes');
		try{
			let attResp = await startRegistration(await resp.json());
			const verificationResp = await fetch('/api/verifyRegister?username='+username, {
				method: 'POST',
				headers: {
				  'Content-Type': 'application/json',
				},
				body: JSON.stringify(attResp),
			  });
			  const verificationJSON = await verificationResp.json();
			  if (verificationJSON && verificationJSON.verified) {
				console.log('success');
			  } else {
				console.log('failed',verificationJSON);

			  }
		} catch(err:Error){
			console.log(err);
			
		}
	}
	const login = async () => {
		const resp = await fetch('/api/login?username='+username);
		console.log(resp);
		try{
		let asseResp = await startAuthentication(await resp.json());
		}
		catch(e){
			console.log(e);
		}
		// const verificationResp = await fetch('/api/startLogin', {
		// 	method: 'POST',
		// 	headers: {
		// 	  'Content-Type': 'application/json',
		// 	},
		// 	body: JSON.stringify(asseResp),
		//   });
		// const verificationJSON = await verificationResp.json();
		// if (verificationJSON && verificationJSON.verified) {
		// 	alert('login success');
		// } else {
		// 	alert('login failed');
		// }

	}
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
		<input placeholder="username" onChange={e=>setUsername(e.target.value)} />
      <button onClick={()=>register()}>Register</button>
	  <button onClick={()=>login()}>Login</button>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
