import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SimpleWebAuthnBrowser from '@simplewebauthn/browser';
import { startRegistration } from '@simplewebauthn/browser';
import {useState, useEffect} from 'react';
import { startAuthentication } from '@simplewebauthn/browser';

const Home: NextPage = () => {
	const [response, setResponse] = useState('');
	const [username, setUsername] = useState('');

	const register = async () => {
	    const resp:any = await (await fetch('/api/register?username='+username)).json();
		if(resp.error){
			console.log(resp.error);
			setResponse(resp.error);
			return;
		}
		try{
			let attResp = await startRegistration(await resp);
			const verificationResp = await fetch('/api/verifyRegister?username='+username, {
				method: 'POST',
				headers: {
				  'Content-Type': 'application/json',
				},
				body: JSON.stringify(attResp),
			  });
			  const verificationJSON = await verificationResp.json();
			  if (verificationJSON && verificationJSON.verified) {
				console.log('registration successful');
				setResponse('register success');
			  } else {
				console.log('registration failed');
				setResponse('register failed');


			  }
		} catch(err){
			console.log(err);
		}
	}

	async function login () {
		const resp:any = await (await fetch('/api/login?username='+username)).json();
		if(resp.error){
			console.log(resp.error);
			setResponse(resp.error);
			return;
		}
		let asseResp = await startAuthentication(await resp);
		const verificationResp = await fetch('/api/startLogin?username='+username, {
				method: 'POST',
				headers: {
				'Content-Type': 'application/json',
				},
				body: JSON.stringify(asseResp),
			});
			const verificationJSON = await verificationResp.json();
			if (verificationJSON && verificationJSON.verified) {
				console.log('you have logged in');
				setResponse('logged in');
			} else {
				console.log('failed to authenticate');
				setResponse('login failed');
			}
	}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
		<input placeholder="username" onChange={e=>setUsername(e.target.value)} />
      <button onClick={()=>register()}>Register</button>
	  <button id='yes' onClick={()=>login()}>Login</button>
	<p>{response}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
